[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@9 && npx pnpm install --frozen-lockfile --prod=false"
]

[phases.build]
cmds = [
  "npx pnpm run build"
]

[start]
cmd = "npx pnpm start"